### ISSUE TITLE
Update documentation / add Wiki

### ISSUE THREAD

**Issue by milkybytes** [milkytoasto/DSChaosMod#8]
When this is released to the public I'd like to have better documentation in the README and potentially a Wiki for contributing / reference material. I'm thinking the README could just be a simple installation and execution guide for end-users with no coding experience, and a link to the wiki for more detailed information on contributing. Potentially a list of credits as well.

i.e. I could possibly add some reference to how to add a new effect, add in a new game, or bots aside from the TwitchBot (if this ends up needing to be used for Discord / YouTube voting, or just as a randomizer).

This may be put on hold until I create an initial .exe file to run the app, though.

**Comment by milkytoasto** [comment]
Unarchiving as this has been resolved with making the repo public and adding a basic Wiki.
